---
apiVersion: apps/v1
kind: Deployment  # The 'kind' field specifies the type of resource that you want to create. In this case, you want to create a Deployment resource.
metadata:
  name: busybox
  namespace: default  # The 'namespace' field specifies the namespace in which you want to create the Deployment resource.
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        # Keep the container running
        command: [ "/bin/sh", "-c", "--" ]  
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi