---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-load-balancer
  namespace: development
spec:
  selector:
    app: booking-service-pod  # The selector field specifies the pods that the Service will route traffic to. In this case, the Service will route traffic to pods with the label app: booking-service-pod.
  ports:
    - port: 80
      targetPort: 3000  
  type: LoadBalancer  # The type field specifies the type of Service. In this case, the Service is of type LoadBalancer.  
